owner: movratrack
repo: status

sites:
  - name: API
    url: https://app.movratrack.com.br/health
    icon: https://app.movratrack.com.br/favicon.ico

  - name: Aplicação Web
    url: https://app.movratrack.com.br
    icon: https://app.movratrack.com.br/favicon.ico

  - name: Listener (GPS)
    check: "tcp-ping"
    url: 172.212.185.45
    port: 7001

status-website:
  cname: status.movratrack.com.br
  name: MovraTrack Status
  theme: light
  introTitle: "**MovraTrack** está no ar"
  introMessage: Status em tempo real dos serviços MovraTrack. Se houver algum problema, abriremos um incidente automaticamente.
  navbar:
    - title: Status
      href: /
    - title: MovraTrack
      href: https://movratrack.com.br

i18n:
  activeIncidents: Incidentes ativos
  allSystemsOperational: Todos os sistemas operacionais
  incidentReport: "Relatório de incidente para $NUMBER"
  activeIncidentSummary: "Aberto em $DATE"
  incidentCompleteTitle: "Resolvido"
  pastIncidents: Incidentes passados
  pastIncidentsResolved: Resolvido em $DURATION
  liveStatus: Status ao vivo
  responseTime: Tempo de resposta
  uptime: Uptime
  ms: ms
  loading: Carregando
  navContactUs: Contato
